name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=file_optimiser --icon=icon.ico --version-file=version_info.txt main.py

    - name: Update Latest Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/file_optimiser.exe"
        tag: "latest"
        name: "Latest Build"
        body: "Automated build of the latest master branch commit."
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: true